title: "Myriad Insights"
description: "Enterprise Security, Built for Small Business."
url: "https://myriadsecurity.github.io"   # change to your custom domain when ready
logo: /assets/images/logo.svg

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "myriad"   # custom skin below
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
defaults:
  - scope: { path: "" }
    values:
      layout: single
      author_profile: false
      toc: false
      classes: wide

# Build
markdown: kramdown
permalink: pretty
include: [".well-known"]
exclude: ["README.md","node_modules","vendor","tmp",".bundle","Gemfile.lock"]

# Social/SEO
author:
  name: "Myriad Insights"
  email: "gscott@myriadinsights.net"

# Footer text
footer:
  links: []
